version: '3.8'

services:
  myapp:
    container_name: myapp
    build: .
    restart: always
    ports:
      - "27017:27017"
    links:
      - postgres
    depends_on:
      - postgres
    networks:
      - scrap_net

  postgres:
    container_name: postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root 
      POSTGRES_PASSWORD: root 
      POSTGRES_DB: notebooks
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    networks:
      - scrap_net



networks:
  scrap_net:

volumes:
  postgres:
